server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:7080/realms/page-pal

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  keycloak:
    admin:
      clientId: spring-authentication-page-pal-id
      clientSecret: VKc0vzjPZSmZNH42VTCPkOFckjNoEVgo
    realm: page-pal
    serverUrl: http://localhost:7080