server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/page_pal
    username: mnmr1996development
    password: mnmr1996development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:7080/realms/page-pal
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka